// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for UserRequestRole.
const (
	UserRequestRoleAdmin  UserRequestRole = "admin"
	UserRequestRoleGuest  UserRequestRole = "guest"
	UserRequestRolePlayer UserRequestRole = "player"
)

// Defines values for UserResponseRole.
const (
	UserResponseRoleAdmin  UserResponseRole = "admin"
	UserResponseRoleGuest  UserResponseRole = "guest"
	UserResponseRolePlayer UserResponseRole = "player"
)

// GameRequest defines model for GameRequest.
type GameRequest struct {
	// Description A brief description of the game
	Description *string `json:"description,omitempty"`

	// EndTime The end time of the game
	EndTime time.Time `json:"end_time"`

	// StartTime The start time of the game
	StartTime time.Time `json:"start_time"`
}

// GameResponse defines model for GameResponse.
type GameResponse struct {
	// Description A brief description of the game
	Description *string `json:"description,omitempty"`

	// EndTime The end time of the game
	EndTime time.Time `json:"end_time"`

	// Id Unique identifier for the game
	Id openapi_types.UUID `json:"id"`

	// StartTime The start time of the game
	StartTime time.Time `json:"start_time"`
}

// ResultRequest defines model for ResultRequest.
type ResultRequest struct {
	// GameId Identifier of the game this result is for
	GameId string `json:"game_id"`

	// Rank The rank achieved by the team in this game
	Rank int `json:"rank"`

	// Score The score achieved by the team
	Score int `json:"score"`

	// TeamId Identifier of the team this result belongs to
	TeamId string `json:"team_id"`
}

// ResultResponse defines model for ResultResponse.
type ResultResponse struct {
	// GameId Identifier of the game this result is for
	GameId string `json:"game_id"`

	// Id Unique identifier for the result entry
	Id openapi_types.UUID `json:"id"`

	// Rank The rank achieved by the team in this game
	Rank int `json:"rank"`

	// Score The score achieved by the team
	Score int `json:"score"`

	// TeamId Identifier of the team this result belongs to
	TeamId string `json:"team_id"`
}

// ServiceRequest defines model for ServiceRequest.
type ServiceRequest struct {
	// Author Author of the service
	Author string `json:"author"`

	// Description A brief description of the service
	Description *string `json:"description,omitempty"`

	// IsPublic Boolean indicating if the service is public
	IsPublic bool `json:"is_public"`

	// LogoUrl URL to the logo of the service
	LogoUrl *string `json:"logo_url,omitempty"`

	// Name Name of the service
	Name string `json:"name"`
}

// ServiceResponse defines model for ServiceResponse.
type ServiceResponse struct {
	// Author Author of the service
	Author string `json:"author"`

	// Description A brief description of the service
	Description *string `json:"description,omitempty"`

	// Id Unique identifier for the service
	Id openapi_types.UUID `json:"id"`

	// IsPublic Boolean indicating if the service is public
	IsPublic bool `json:"is_public"`

	// LogoUrl URL to the logo of the service
	LogoUrl *string `json:"logo_url,omitempty"`

	// Name Name of the service
	Name string `json:"name"`
}

// TeamRequest defines model for TeamRequest.
type TeamRequest struct {
	// AvatarUrl URL to the team's avatar
	AvatarUrl *string `json:"avatar_url,omitempty"`

	// Description A brief description of the team
	Description *string `json:"description,omitempty"`

	// Name Name of the team
	Name string `json:"name"`

	// SocialLinks JSON string containing social media links of the team
	SocialLinks *string `json:"social_links,omitempty"`

	// UniversityId University or institution the team is associated with
	UniversityId int `json:"university_id"`
}

// TeamResponse defines model for TeamResponse.
type TeamResponse struct {
	// AvatarUrl URL to the team's avatar
	AvatarUrl *string `json:"avatar_url,omitempty"`

	// Description A brief description of the team
	Description *string `json:"description,omitempty"`

	// Id Unique identifier for the team
	Id openapi_types.UUID `json:"id"`

	// Name Name of the team
	Name string `json:"name"`

	// SocialLinks JSON string containing social media links of the team
	SocialLinks *string `json:"social_links,omitempty"`

	// University University or institution the team is associated with
	University *string `json:"university,omitempty"`
}

// UniversitiesResponse defines model for UniversitiesResponse.
type UniversitiesResponse = []UniversityResponse

// UniversityResponse defines model for UniversityResponse.
type UniversityResponse struct {
	// Id The unique identifier of the university
	Id openapi_types.UUID `json:"id"`

	// Name The name of the university
	Name string `json:"name"`
}

// UserRequest defines model for UserRequest.
type UserRequest struct {
	// AvatarUrl URL to the user's avatar
	AvatarUrl *string `json:"avatar_url,omitempty"`

	// DisplayName The name of the user
	DisplayName *string `json:"display_name,omitempty"`

	// Password User password
	Password *string `json:"password,omitempty"`

	// Role The role of the user (admin, player or guest)
	Role *UserRequestRole `json:"role,omitempty"`

	// Status Status of the user (active, disabled)
	Status  *string               `json:"status,omitempty"`
	TeamIds *[]openapi_types.UUID `json:"team_ids,omitempty"`

	// UserName The login of the user
	UserName *string `json:"user_name,omitempty"`
}

// UserRequestRole The role of the user (admin, player or guest)
type UserRequestRole string

// UserResponse defines model for UserResponse.
type UserResponse struct {
	// AvatarUrl URL to the user's avatar
	AvatarUrl *string `json:"avatar_url,omitempty"`

	// DisplayName The name of the user
	DisplayName *string `json:"display_name,omitempty"`

	// Id The unique identifier for the user
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Role The role of the user (admin, player or guest)
	Role *UserResponseRole `json:"role,omitempty"`

	// Status Status of the user (active, disabled)
	Status *string `json:"status,omitempty"`

	// UserName The login of the user
	UserName *string `json:"user_name,omitempty"`
}

// UserResponseRole The role of the user (admin, player or guest)
type UserResponseRole string

// PostApiV1AuthSigninJSONBody defines parameters for PostApiV1AuthSignin.
type PostApiV1AuthSigninJSONBody struct {
	Password *string `json:"password,omitempty"`
	UserName *string `json:"user_name,omitempty"`
}

// PostApiV1ServicesUuidUploadCheckerMultipartBody defines parameters for PostApiV1ServicesUuidUploadChecker.
type PostApiV1ServicesUuidUploadCheckerMultipartBody struct {
	File *openapi_types.File `json:"file,omitempty"`
}

// PostApiV1ServicesUuidUploadServiceMultipartBody defines parameters for PostApiV1ServicesUuidUploadService.
type PostApiV1ServicesUuidUploadServiceMultipartBody struct {
	File *openapi_types.File `json:"file,omitempty"`
}

// GetApiV1UniversitiesParams defines parameters for GetApiV1Universities.
type GetApiV1UniversitiesParams struct {
	// Term Optional search term to filter universities by name.
	Term *string `form:"term,omitempty" json:"term,omitempty"`
}

// PostApiV1AuthSigninJSONRequestBody defines body for PostApiV1AuthSignin for application/json ContentType.
type PostApiV1AuthSigninJSONRequestBody PostApiV1AuthSigninJSONBody

// CreateGameJSONRequestBody defines body for CreateGame for application/json ContentType.
type CreateGameJSONRequestBody = GameRequest

// UpdateGameJSONRequestBody defines body for UpdateGame for application/json ContentType.
type UpdateGameJSONRequestBody = GameRequest

// CreateResultJSONRequestBody defines body for CreateResult for application/json ContentType.
type CreateResultJSONRequestBody = ResultRequest

// CreateServiceJSONRequestBody defines body for CreateService for application/json ContentType.
type CreateServiceJSONRequestBody = ServiceRequest

// UpdateServiceJSONRequestBody defines body for UpdateService for application/json ContentType.
type UpdateServiceJSONRequestBody = ServiceRequest

// PostApiV1ServicesUuidUploadCheckerMultipartRequestBody defines body for PostApiV1ServicesUuidUploadChecker for multipart/form-data ContentType.
type PostApiV1ServicesUuidUploadCheckerMultipartRequestBody PostApiV1ServicesUuidUploadCheckerMultipartBody

// PostApiV1ServicesUuidUploadServiceMultipartRequestBody defines body for PostApiV1ServicesUuidUploadService for multipart/form-data ContentType.
type PostApiV1ServicesUuidUploadServiceMultipartRequestBody PostApiV1ServicesUuidUploadServiceMultipartBody

// CreateTeamJSONRequestBody defines body for CreateTeam for application/json ContentType.
type CreateTeamJSONRequestBody = TeamRequest

// UpdateTeamJSONRequestBody defines body for UpdateTeam for application/json ContentType.
type UpdateTeamJSONRequestBody = TeamRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = UserRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UserRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Validate current session and return user role
	// (GET /api/v1/auth/session)
	ValidateSession(w http.ResponseWriter, r *http.Request)
	// Sign in user
	// (POST /api/v1/auth/signin)
	PostApiV1AuthSignin(w http.ResponseWriter, r *http.Request)
	// Logout user
	// (POST /api/v1/auth/signout)
	PostApiV1AuthSignout(w http.ResponseWriter, r *http.Request)
	// List all games
	// (GET /api/v1/games)
	ListGames(w http.ResponseWriter, r *http.Request)
	// Create a new game
	// (POST /api/v1/games)
	CreateGame(w http.ResponseWriter, r *http.Request)
	// Delete a game
	// (DELETE /api/v1/games/{uuid})
	DeleteGame(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Get a game by ID
	// (GET /api/v1/games/{uuid})
	GetGameById(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Update a game
	// (PUT /api/v1/games/{uuid})
	UpdateGame(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// List all results
	// (GET /api/v1/results)
	ListResults(w http.ResponseWriter, r *http.Request)
	// Create a new result
	// (POST /api/v1/results)
	CreateResult(w http.ResponseWriter, r *http.Request)
	// Get a result by ID
	// (GET /api/v1/results/{uuid})
	GetResultById(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// List all services
	// (GET /api/v1/services)
	ListServices(w http.ResponseWriter, r *http.Request)
	// Create a new service
	// (POST /api/v1/services)
	CreateService(w http.ResponseWriter, r *http.Request)
	// Delete a service
	// (DELETE /api/v1/services/{uuid})
	DeleteService(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Get a service by ID
	// (GET /api/v1/services/{uuid})
	GetServiceById(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Update a service
	// (PUT /api/v1/services/{uuid})
	UpdateService(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Upload zip-archive
	// (POST /api/v1/services/{uuid}/upload/checker)
	PostApiV1ServicesUuidUploadChecker(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Upload zip service
	// (POST /api/v1/services/{uuid}/upload/service)
	PostApiV1ServicesUuidUploadService(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// List all teams
	// (GET /api/v1/teams)
	ListTeams(w http.ResponseWriter, r *http.Request)
	// Create a new team
	// (POST /api/v1/teams)
	CreateTeam(w http.ResponseWriter, r *http.Request)
	// Delete a team
	// (DELETE /api/v1/teams/{uuid})
	DeleteTeam(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Get a team by ID
	// (GET /api/v1/teams/{uuid})
	GetTeamById(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Update a team
	// (PUT /api/v1/teams/{uuid})
	UpdateTeam(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Retrieves a list of universities
	// (GET /api/v1/universities)
	GetApiV1Universities(w http.ResponseWriter, r *http.Request, params GetApiV1UniversitiesParams)
	// List all users
	// (GET /api/v1/users)
	ListUsers(w http.ResponseWriter, r *http.Request)
	// Create a new user
	// (POST /api/v1/users)
	CreateUser(w http.ResponseWriter, r *http.Request)
	// Delete a user
	// (DELETE /api/v1/users/{uuid})
	DeleteUser(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Get a user by ID
	// (GET /api/v1/users/{uuid})
	GetUserById(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Update a user
	// (PUT /api/v1/users/{uuid})
	UpdateUser(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Validate current session and return user role
// (GET /api/v1/auth/session)
func (_ Unimplemented) ValidateSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Sign in user
// (POST /api/v1/auth/signin)
func (_ Unimplemented) PostApiV1AuthSignin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout user
// (POST /api/v1/auth/signout)
func (_ Unimplemented) PostApiV1AuthSignout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all games
// (GET /api/v1/games)
func (_ Unimplemented) ListGames(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new game
// (POST /api/v1/games)
func (_ Unimplemented) CreateGame(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a game
// (DELETE /api/v1/games/{uuid})
func (_ Unimplemented) DeleteGame(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a game by ID
// (GET /api/v1/games/{uuid})
func (_ Unimplemented) GetGameById(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a game
// (PUT /api/v1/games/{uuid})
func (_ Unimplemented) UpdateGame(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all results
// (GET /api/v1/results)
func (_ Unimplemented) ListResults(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new result
// (POST /api/v1/results)
func (_ Unimplemented) CreateResult(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a result by ID
// (GET /api/v1/results/{uuid})
func (_ Unimplemented) GetResultById(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all services
// (GET /api/v1/services)
func (_ Unimplemented) ListServices(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new service
// (POST /api/v1/services)
func (_ Unimplemented) CreateService(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a service
// (DELETE /api/v1/services/{uuid})
func (_ Unimplemented) DeleteService(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a service by ID
// (GET /api/v1/services/{uuid})
func (_ Unimplemented) GetServiceById(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a service
// (PUT /api/v1/services/{uuid})
func (_ Unimplemented) UpdateService(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Upload zip-archive
// (POST /api/v1/services/{uuid}/upload/checker)
func (_ Unimplemented) PostApiV1ServicesUuidUploadChecker(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Upload zip service
// (POST /api/v1/services/{uuid}/upload/service)
func (_ Unimplemented) PostApiV1ServicesUuidUploadService(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all teams
// (GET /api/v1/teams)
func (_ Unimplemented) ListTeams(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new team
// (POST /api/v1/teams)
func (_ Unimplemented) CreateTeam(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a team
// (DELETE /api/v1/teams/{uuid})
func (_ Unimplemented) DeleteTeam(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a team by ID
// (GET /api/v1/teams/{uuid})
func (_ Unimplemented) GetTeamById(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a team
// (PUT /api/v1/teams/{uuid})
func (_ Unimplemented) UpdateTeam(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieves a list of universities
// (GET /api/v1/universities)
func (_ Unimplemented) GetApiV1Universities(w http.ResponseWriter, r *http.Request, params GetApiV1UniversitiesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all users
// (GET /api/v1/users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new user
// (POST /api/v1/users)
func (_ Unimplemented) CreateUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a user
// (DELETE /api/v1/users/{uuid})
func (_ Unimplemented) DeleteUser(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a user by ID
// (GET /api/v1/users/{uuid})
func (_ Unimplemented) GetUserById(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a user
// (PUT /api/v1/users/{uuid})
func (_ Unimplemented) UpdateUser(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ValidateSession operation middleware
func (siw *ServerInterfaceWrapper) ValidateSession(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ValidateSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostApiV1AuthSignin operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1AuthSignin(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1AuthSignin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostApiV1AuthSignout operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1AuthSignout(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1AuthSignout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListGames operation middleware
func (siw *ServerInterfaceWrapper) ListGames(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGames(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateGame operation middleware
func (siw *ServerInterfaceWrapper) CreateGame(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGame(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteGame operation middleware
func (siw *ServerInterfaceWrapper) DeleteGame(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGame(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetGameById operation middleware
func (siw *ServerInterfaceWrapper) GetGameById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGameById(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateGame operation middleware
func (siw *ServerInterfaceWrapper) UpdateGame(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateGame(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListResults operation middleware
func (siw *ServerInterfaceWrapper) ListResults(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListResults(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateResult operation middleware
func (siw *ServerInterfaceWrapper) CreateResult(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateResult(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetResultById operation middleware
func (siw *ServerInterfaceWrapper) GetResultById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetResultById(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListServices operation middleware
func (siw *ServerInterfaceWrapper) ListServices(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListServices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateService operation middleware
func (siw *ServerInterfaceWrapper) CreateService(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateService(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteService operation middleware
func (siw *ServerInterfaceWrapper) DeleteService(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteService(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetServiceById operation middleware
func (siw *ServerInterfaceWrapper) GetServiceById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetServiceById(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateService operation middleware
func (siw *ServerInterfaceWrapper) UpdateService(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateService(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostApiV1ServicesUuidUploadChecker operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1ServicesUuidUploadChecker(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1ServicesUuidUploadChecker(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostApiV1ServicesUuidUploadService operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1ServicesUuidUploadService(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1ServicesUuidUploadService(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListTeams operation middleware
func (siw *ServerInterfaceWrapper) ListTeams(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTeams(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateTeam operation middleware
func (siw *ServerInterfaceWrapper) CreateTeam(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTeam(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteTeam operation middleware
func (siw *ServerInterfaceWrapper) DeleteTeam(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTeam(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetTeamById operation middleware
func (siw *ServerInterfaceWrapper) GetTeamById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTeamById(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateTeam operation middleware
func (siw *ServerInterfaceWrapper) UpdateTeam(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTeam(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetApiV1Universities operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1Universities(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1UniversitiesParams

	// ------------- Optional query parameter "term" -------------

	err = runtime.BindQueryParameter("form", true, false, "term", r.URL.Query(), &params.Term)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "term", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1Universities(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUser(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetUserById operation middleware
func (siw *ServerInterfaceWrapper) GetUserById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserById(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUser(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/session", wrapper.ValidateSession)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/signin", wrapper.PostApiV1AuthSignin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/signout", wrapper.PostApiV1AuthSignout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/games", wrapper.ListGames)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/games", wrapper.CreateGame)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/games/{uuid}", wrapper.DeleteGame)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/games/{uuid}", wrapper.GetGameById)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/games/{uuid}", wrapper.UpdateGame)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/results", wrapper.ListResults)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/results", wrapper.CreateResult)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/results/{uuid}", wrapper.GetResultById)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/services", wrapper.ListServices)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/services", wrapper.CreateService)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/services/{uuid}", wrapper.DeleteService)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/services/{uuid}", wrapper.GetServiceById)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/services/{uuid}", wrapper.UpdateService)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/services/{uuid}/upload/checker", wrapper.PostApiV1ServicesUuidUploadChecker)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/services/{uuid}/upload/service", wrapper.PostApiV1ServicesUuidUploadService)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/teams", wrapper.ListTeams)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/teams", wrapper.CreateTeam)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/teams/{uuid}", wrapper.DeleteTeam)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/teams/{uuid}", wrapper.GetTeamById)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/teams/{uuid}", wrapper.UpdateTeam)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/universities", wrapper.GetApiV1Universities)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/users", wrapper.CreateUser)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/users/{uuid}", wrapper.DeleteUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/users/{uuid}", wrapper.GetUserById)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/users/{uuid}", wrapper.UpdateUser)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xb73LbxhF/lRu0M01mSJGyJSVlJh9kuXGUcRKPJedDU43mCCzJi4E7+O5Ah9VoJn/6",
	"AP3cp1CbZsZtxukrgG/UuT8AAfDAPxClUqq/2BRxt7u3+9vf7R4PF57PophRoFJ4vQtP+COIsP74BEfw",
	"HF4lIKT6M+YsBi4J6IcBCJ+TWBJG5/70DlGfExigwreIDZAcARriCLyWJycxeD1PSE7o0LtseUCDc0ki",
	"mBd2OgIENEDqaUUKfIujOFSCHnS73XZ3t/1g77S719s/6HU/2Ol2u3/0Wt6A8QhLr+cFWEJb63DoFxJz",
	"ucAC/XxFGx42suGy5XF4lRAOgdf7euaQkm1n+TTW/wZ8qUw3cRIxowLuf6BIMK/5BSWvEkAkACrJgABH",
	"A8aL+nPRSUKCuxZ+bfESDDwHkYSyNluVsecuzx3PXFZYF5IjIhDXMhERypsup3FMX7rdpZ4g7I8IjCFA",
	"/YmWLAFHiFAjvAwvQiUMgetI+IzXBUE9cop1SlIPVly0Nq246D6EjA4FkmxppDLfWn9kK5jpXxSvuqy9",
	"mYCtlztWHFDJJ6vk0Ds4KDho3zTCxAnwMfHrt1ycyBHjDhLX32e2CyPFFaCmW8ECkUScx0k/JP68wEeM",
	"hYApIjQgPpaEDhEpyVNAtZNzyX0zSYkO2ZCdJzx0QPb5UySZFqUGrWAmxS5i/wLP6Lx2ciW8NgjFlVvx",
	"C0Nal+dbGdO1WGImaClB/B+DJVgVMaeAo3oGGGOJ+dJ1KpL5nUBm9CZBU+bWdTxWN1Mwn+DwPCT05Xy1",
	"6n128uUXyAxGPqMSE6o+mkkogoBgpKcuU5NQMgYuiJyc16DbPkaMI0KFJDLRC59tVAJhoRVLCNBrIkeO",
	"TaYSfmo2tbLy+qDXcsSWRn09nrBSlpLEHcLSxoG0qKSoZYxcJwFRBBGREGk//JbDwOt5v+nMOv2ObfM7",
	"M4PzqZe5Dsw5npRUTOpR6kKDqtKSOURY/xb8WGyjPtyF3Q/8/kF73987aO/9/uFeu38Q7Lf3/Q8f7h98",
	"sPvA7x80x5GyiBawVGNE+tf0bXqV/mf6ffrv9E36LzT9S/om/SV9k16lv6D0b9Mf07+nV+lb/fzX9Kf0",
	"V6T+mX4//TH9Z3o1/W76/fSH9B/pz+nb9G024Cr9afqdeph/Nf0xfZu+UePUjPTN9If05+kP6dV1ESGA",
	"X3cPSQTwxWxCRBziyfmKfhbglBJjIV4z7mISARzlj13tBgtrFKsnRcXoPRxEhLaQMlgBkKOhcs77KuY0",
	"ifRWrUZ4Lc8MUSW8dt9ZERX5M9fxgUwcpHOiv6/Y4ksyhhYKiMD9EIL3XQJtnyBKidywcdt8blX5QS1s",
	"ARBCNiR0MRIua2F8zV3xlnC8OvtlQbKSlnfV9xnmNwEc9RWhA6ZE6o3eVyxYrX+8w2fHOhYRpnioKoGj",
	"00/Qe0c4lgkHpLR/EuLh+/pkQrT03i1a2gjRQpgGWRMgdpRRRGrXKRmfK4EQAZXo8Nmx1/L0BqN17u50",
	"d7pq3SwGimPi9byH+itFhHKkPdvBMemMdzuqd+gIEMKWa0OQ8046GoH/MuuU/IRzpdVOUpXGGIck0NZy",
	"kAmnxZRQ8FG2q6TCSt5x4PW8r9QMLOHEalb7jklBbd2DbjfzK1BtEI7jULdsjHa+EcZWU13M5+xqOZat",
	"wwZ8Bkze7Uq17yVhqCDl9SRPoHHK1KrJcmSpHu1dx3mS6WFBLAuMo5N1w7mSbVbM2IRKfTSMr6eLJIow",
	"nxRCOae/gAedq9pfLU/ioVAcYeUL70zJK+ORDCnRIY6ZkO5jC8V0ZvnYiO9PUJ7nWne2q7fMsboaSOF1",
	"Zl6rYJ96lFntM/aSOBD7jAl5GJOvdpXyE2OgqZZAyEcsmFwDsMXyZAYQ++kZFqLI4IuKlRLRzUl6sQa1",
	"zcpAhcrLjeZngCUuG6irsJANhxAg7deVbHRUcrkMJBLfByEGSRhOdtBhJb4qOQRIFeYR4AC4NuwEZPtI",
	"P3dsPuX5r0fEHyEKEAhVA/QBEeqHSZAp7wuFDCqRRYjm75lDZku3dp2T4GPc93cfPPwIPcNy9HHnI/Q5",
	"/rZ9OISPH+7tH3S7H6FPpYy/pOHE4R/ljj0TlCpLGHK2ZqC+QqoevFs/eJZHrFAcX7a8fbcKCZziEJ0A",
	"HwNHf+Cc8QpJqIRRjsl219U4gCVyy0lAWXiHcoMlcoXE4BCxMbzLjVvKjacmLiulhi4TC3VaGZ5PiZBP",
	"9IhrYnKlQ53ShYBqu9byvm1bde3sQVWlA6iHKCRCqtrJrLQudI9wHraqN9V8HIZWwMyhxjFnl62cT8rO",
	"O+KAJTwxh6lN9/Xl/spsXnWPLa9byUC+tjQoZfJqnqpB6SeYhKCGZcEsedQ4xhJn9gtqxalViHYu1H/H",
	"waVRFoKEeY8/1t9bj8eY4wikZpuvFQnEIQvA6w1wKEC1Wrr00ceYpsDxjAav6kc3lWzqTELIiaEmogVf",
	"nq0cNeOFW4uacS7CdRFruSnkCWgGeTTRnr1fQdlgFucun2OwxyBNXAg1dtufOGwgbi7gT0BaJaoKOn7s",
	"pr7EEfMXcYDvRR5uMWcn2se12b+qsQ7A5aiogmcTMp1IM3ipp5bCZmBODBZXLM/tmNuoWSoXom6kakHZ",
	"omsKE56vN3Nc5oFlxYkZd0PlSfluX1OwGyk1JUp9WcGzlc27ZB5NnQvzwZYXdfuYEdF4J8t03OO9rJoN",
	"6+xmzrNAswdlt9kqu5AzpNnx9kKGOMkG3QZFVC9TbZwj8iXX8IOYrXbWDNqvljHESX5l6CYoonJ1sClH",
	"WDFrk0ThPtS8XxyY6lzYTyv1ITPXrc8VuZ670I1k7nc3JO4mYqHr61sJO6gxB2+5XzebVE1YOIuLi4az",
	"K41VHi6TSX1DcG8SYuuJ0N0cuGvu65BgJ4lDhoOOPwL/JfD6s/VPMQ1Ce4vAzEF/JnEbc39ExqCvkyEr",
	"5E+0/pQ8s+wks+CFlnVk1c8Ba2uAtBg3URJKEmMuO0pMOzuyrzvSHxDzO3Gus08o5pNb/CXO8eOuQZoN",
	"7hzWqhG/FtoyxNaibaYPlRCWEZjPAkAkwkMQ+vcakP7Ozk4D4NUy2jvgbRnwVqY5fWFmYfNwqkfcRudQ",
	"ul+98bbBrPSOHhnlzY200ciiaqKzrK05NZekb2IrL74J0XQfVzKW/Spzp8JVaruyG+qViFWTsHOh/lup",
	"1bLhXL+sNBruQpOlIbFOh1Xj5freSo1o3FhtsyM3mNZNWiodCFc/pd+rqDZTBf6q76TuAd63mHjX6Z7W",
	"5bLON4zQzkUigFtmc29TeeWpJZ7qyZ8xQl/oifOxn78zevy48kZQMzgsqy9bi3XbSygO3Um2kua6zzZ6",
	"UyoCIfBQ7zENbkQdMUrBlwvPHu0QfbFMNyRroycEPIaG8Hmq5r7Dz5bi5ykMFoJHR89AZ8BZtAJ0ksIL",
	"drU38U9HRCCgQcyIvj8nOYExCFScvIOOJfIxRUzPwmE4QQMSSuClYUiOsEQRlv4IYSRi8MmA+EgCj1y9",
	"9RMwCC2+B7gMl19aA5AA1dhr2UgypzX9ib6dv5Oh51UCulXNocuj0i3BTYNjpdcXi+8+Ops1/fqnbvhU",
	"RpRCWsbH8zx0OO/wkrJrM6zMXousAEbYq5m1re8LPeI2Wt/SS1Qbb33NSptdi8k7z8Q6I3er/ntZ52nv",
	"zN9EAVR8f7JpAaQv9v4v7wNWbq1mTq3CtLQHLm4OrcfXL5ZX2GG2pDnUUau7D3jTvX3ecdaErr7jVCMa",
	"d5zbHJ0NpnOTjlMH4qYvBmavR5S61wIH1nev9yAht5i8l1wM3DQY8k64jrjVaP2ugquge8ZZkPgauWaQ",
	"1/L0q9HeSMpY9DodXw66u8GOzyJvvlc4keYd2Jq5wjzeWSjjKfNx6JLQ63RC9WzEhOzt7XYfeJdnl/8N",
	"AAD//x12qXh4UgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
